/*

 SLOTSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : G:\Projects\Homebrew Game Dev\Gameboy\Slots\Graphics\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define slotsWidth 10
#define slotsHeight 10
#define slotsBank 0

extern unsigned char slots[];

/* End of SLOTSMAP.H */
