/*

 SLOTSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : G:\Projects\Homebrew Game Dev\Gameboy\gbslots\Graphics\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define slotsmapWidth 32
#define slotsmapHeight 32
#define slotsmapBank 0

extern unsigned char slotsmap[];

/* End of SLOTSMAP.H */
